version: 1.0.{build}
configuration: Release

before_build:
  - nuget restore src/MarkSite.sln

build:
  project: src/MarkSite.sln
  verbosity: minimal

build_script:
  - test\aspnet_compiler -p src -v -u output

test_script:
  - ps: .\test\test.ps1 -ExitOnError
