version: 1.0.{build}
configuration: Release

install:
  - npm install
  - npm install gulp -g

build:
  verbosity: minimal

build_script: 
  - test\aspnet_compiler -p src -v -u output
  - gulp

test_script:
  - ps: .\test\test.ps1
